//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietThuePhong
    {
        [DisplayName("Mã thuê phòng")]
        public int MaThuePhong { get; set; }


        public int MaKhachHang { get; set; }

        [DisplayName("Số lượng khách")]
        [Required(ErrorMessage = "Số lượng khách không được bỏ trống")]
        public Nullable<int> SoLuongKhach { get; set; }


        public virtual KhachHang KhachHang { get; set; }
        public virtual ThuePhong ThuePhong { get; set; }
    }
}
