//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDoanhThu
    {
        [Required(ErrorMessage = "Mã doanh thu không được bỏ trống")]
        [DisplayName("Mã doanh thu")]
        public int MaDoanhThu { get; set; }


        public Nullable<int> MaLoai { get; set; }


        [DisplayName("Tháng")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "Tháng {0:MM}")]
        public Nullable<System.DateTime> Thang { get; set; }

        [DisplayName("Doanh thu")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:#,###}VNĐ")]
        public Nullable<decimal> DoanhThu { get; set; }

        [DisplayName("Tỉ lệ")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0}%")]
        public Nullable<decimal> Tile { get; set; }


        public virtual DoanhThu DoanhThu1 { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
