//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChucVu()
        {
            this.NV = new HashSet<NV>();
        }

        [Required(ErrorMessage = "Mã chức vụ không được bỏ trống")]
        [DisplayName("Mã chức vụ")]
        public int MaCV { get; set; }

        [Required(ErrorMessage = "Tên chức vụ không được bỏ trống")]
        [DisplayName("Tên chức vụ")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Tên chức vụ không được quá 20 và ít hơn 3 ký tự")]
        public string TenCV { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV> NV { get; set; }
    }
}
