//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HD()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }

        [Required(ErrorMessage = "Mã hóa đơn không được bỏ trống")]
        [DisplayName("Mã hóa đơn")]
        public int MaHD { get; set; }

        public Nullable<int> MaKhachHang { get; set; }

        public Nullable<int> MaNV { get; set; }

        [DisplayName("Tổng tiền")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:#,###}VNĐ")]
        public Nullable<decimal> TongTien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual NV NV { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
