//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ChiTietThuePhong = new HashSet<ChiTietThuePhong>();
            this.HD = new HashSet<HD>();
        }

        [DisplayName("Mã khách hàng")]
        public int MaKhachHang { get; set; }

        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage = "Tên của khách hàng không được trống")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Tên của KH không được quá 20 và ít hơn 1 ký tự")]
        public string TenKhachHang { get; set; }

        public Nullable<int> MaLoaiKhach { get; set; }

        [DisplayName("Địa chỉ KH ")]
        [Required(ErrorMessage = "Địa chỉ không được bỏ trống")]
        [StringLength(30, ErrorMessage = "Địa chỉ không được quá 30 ký tự")]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Chứng minh dân nhân của khách hàng không được trống")]
        [StringLength(9, MinimumLength = 1, ErrorMessage = "CMND không được quá 9 và ít hơn 1 ký tự")]
        [DisplayName("Chứng minh dân nhân")]
        public string CMND { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuePhong> ChiTietThuePhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD> HD { get; set; }
        public virtual LoaiKhach LoaiKhach { get; set; }
    }
}
