//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NV()
        {
            this.HD = new HashSet<HD>();
        }

        [DisplayName("Mã nhân viên")]
        [Required(ErrorMessage = "Mã nhân viên không được bỏ trống")]
        public int MaNV { get; set; }

        [DisplayName("Tên nhân viên")]
        [Required(ErrorMessage = "Tên nhân viên không được bỏ trống")]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "Tên nhân viên không dược ít hơn 4 ký tự và quá 30 ký tự")]
        public string TenNV { get; set; }

        public Nullable<int> MaCV { get; set; }


        [DisplayName("Số diện thoại")]
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3,4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Sai định dạng số điện thoại")]
        public string SDTNV { get; set; }

        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ không được bỏ trống")]
        [StringLength(30, ErrorMessage = "Địa chỉ không được quá 30 ký tự")]
        public string DCNV { get; set; }


        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD> HD { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
