//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class QuiDinh
    {
        [DisplayName("Mã qui định")]
        public int MaQuiDinh { get; set; }

        [Required(ErrorMessage ="Tên qui định không dược bỏ trống")]
        [StringLength(30,MinimumLength =1,ErrorMessage ="Tên qui định không được quá dài và quá ngắn")]
        [DisplayName("Tên qui định")]
        public string TenQuiDinh { get; set; }
        [Required(ErrorMessage = "Mô tả không dược bỏ trống")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Mô tả không được quá dài và quá ngắn")]
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }

        [DisplayName("Tham số")]
        public Nullable<double> ThamSo { get; set; }

        [DisplayName("Tham số tiền")]
        public Nullable<decimal> ThamSoTien { get; set; }
    }
}
