//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [DisplayName("Mã nhân viên")]
        public int MaNV { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password không được bỏ trống")]
        [DisplayName("Password")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Password không được dưới 4 và trên 20 ký tự")]
        [DataType(DataType.Password)]
        public string Pass { get; set; }

        public string Roles { get; set; }
    
        public virtual NV NV { get; set; }
    }
}
