//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ThuePhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuePhong()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
            this.ChiTietThuePhong = new HashSet<ChiTietThuePhong>();
        }

        [DisplayName("Mã thuê phòng")]
        public int MaThuePhong { get; set; }

        [DisplayName("Mã phòng")]
        public int MaPhong { get; set; }

        [Required(ErrorMessage = "Ngày Thuê Phòng không được bỏ trống")]
        [DisplayName("Ngày thuê phòng")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgayBatDauThue { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThuePhong> ChiTietThuePhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
